[package]
name = "data_analytics_portfolio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
polars = { version = "0.28.0", features = ["lazy", "describe", "sql"] }
