[Workspace]
name = "Data Analytics Portfolio"
workspace = "."
bin = "bin"
log = "log"
src = "src"
assets = "assets"
VERBOSE = true

[Projects]
[Projects.PRJ1]
DB = "nba"
DIR = "src/nba"
DATA = "assets/nba/data/"

[Projects.PRJ2]
DB = "world"
DIR = "src/world"
INIT = "assets/world.sql"
SOURCE = "https://mysqlcode.com/wp-content/uploads/2023/01/world.zip"

[Server]
DATA = "data"
LOG = "log/PostgreSQL.log"
HOST = "localhost"
PORT = "5342"
USER = "$USER"
DB = "postgres"

[DatabaseURL]
DB_URL = "postgres://$PGUSER@$PGHOST:$PGPORT/bookstore"
DB_URL_PRJ1 = "postgres://$PGUSER@$PGHOST:$PGPORT/$PRJ1_DB"
DB_URL_PRJ2 = "postgres://$PGUSER@$PGHOST:$PGPORT/$PRJ2_DB"
