#!/bin/sh

# Establish workspace variables
workspace="$(dirname "$(realpath "$0")")"
project="$(basename "$workspace")"
archive="$workspace/Archive"
bin="$workspace/Bin"
default_host="localhost"
default_port="5432"
default_user="postgres"
default_db="$project"

# Load environment variables from .env file
if [ -f "$workspace/.env" ]; then
  . "$workspace/.env"
fi

# Enable local scripts
for script in "$bin"/*; do
  [ -x "$script" ] || chmod +x "$script"
done


#@ Establish connection variables
# Enable global export of environment variables
set -o allexport

[ "$host" ] || {
  printf "Enter the host (default: %s): " "$default_host"
  read -r host && host="${host:-$default_host}"
}

[ "$port" ] || {
  printf "Enter the port (default: %s): " "$default_port"
  read -r port && port="${port:-$default_port}"
}

[ "$user" ] || {
  printf "Enter the username (default: %s): " "$default_user"
  read -r user && user="${user:-$default_user}"
}

[ "$db" ] || {
  printf "Enter the database name (default: %s): " "$default_db"
  read -r db && db="${db:-$default_db}"
}

# Disable global export of environment variables
set +o allexport

"$bin"/test_db
