CREATE OR REPLACE USER 'user'@localhost IDENTIFIED BY 'password';
CREATE OR REPLACE USER 'user'@'127.0.0.1' IDENTIFIED BY 'password';

GRANT ALL PRIVALAGES ON sqlx.* TO 'user'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVALAGES ON sqlx.* TO 'user'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVALAGES;